# Generated by Django 4.2.11 on 2024-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["created_on"]},
        ),
        migrations.AddField(
            model_name="post",
            name="field_1",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
