# Generated by Django 4.2.11 on 2024-03-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="field_1",),
    ]
