# Generated by Django 4.2.11 on 2024-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_field_1_post_field_2_post_field_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="field_2", field=models.IntegerField(default=1312),
        ),
    ]
